Repository swiftyfinch/Rugby, pull requests merged in 2022-10, with the labels that each got.

#197 🤖 Use CryptoKit instead of CommonCrypto
  Sources/Rugby/Common/Extensions/Crypto/Data+SHA1.swift
Labels: optimisation, Hacktoberfest

#199 🎨 Print config name during building
  Sources/Rugby/Commands/Cache/Steps/CacheBuildStep.swift
Labels: feature, Hacktoberfest

#200 🤖 Remove Xcode 12 build job
  .github/workflows/regress.yml
Labels: Hacktoberfest, ci

#202 🐛 Fixed video in README
  README.md
Labels: docs, Hacktoberfest, awaiting response
