Repository swiftyfinch/Rugby, pull requests merged in 2022-01, with the labels that each got.

#118 🐛 Make parsing external source more flexible
  Sources/Rugby/Commands/Cache/Other/Lockfile/Lockfile.swift
Labels: bug

#119 🐛 Support `fish` shell
  Sources/Rugby/Commands/Cache/Other/Build/XcodeBuild.swift
Labels: bug

#120 🏈 Use Xcode 13 on ci
  .github/workflows/regress.yml
Labels: clean up

#121 Fix wording
  Sources/Rugby/Commands/Cache/Other/PatchConfigs/CacheIntegration.swift
  Sources/Rugby/Commands/Cache/Steps/CacheCleanupStep.swift
  Sources/Rugby/Commands/Cache/Steps/CacheIntegrateStep.swift
Labels: clean up, blocked
