Repository swiftyfinch/Rugby, pull requests merged in 2023-11, with the labels that each got.

#264 ⚙️ Refactor BuildManager
  Sources/RugbyFoundation/Core/Build/BuildManager.swift
  Sources/RugbyFoundation/Vault/Commands/Build/Vault+Build.swift
  Tests/FoundationTests/Mocks/IInternalBuildManagerMock.generated.swift
Labels: clean up

#266 🐛 Use product name instead of module name when patching XCFrameworks
  Sources/RugbyFoundation/Core/Use/SupportFilesPatcher.swift
  Tests/FoundationTests/Core/Use/SupportFilesPatcherTests.swift
Labels: bug

#276 🚀 Add build option `--result-bundle-path`
  Docs/commands-help/build/full.md
  Docs/commands-help/build/pre.md
  Docs/commands-help/shortcuts/cache.md
  Docs/commands-help/use.md
  Docs/commands-help/warmup.md
  Sources/Rugby/Commands/Basic/Build/AdditionalBuildOptions.swift
  Sources/Rugby/Commands/Basic/Build/BuildOptions.swift
  Sources/RugbyFoundation/Core/Build/XcodeBuild/XcodeBuild.swift
  Tests/FoundationTests/Core/Build/BinariesStorageTests.swift
  Tests/FoundationTests/Core/Build/PrebuildManagerTests.swift
  Tests/FoundationTests/Core/Build/XcodeBuild/XcodeBuildTests.swift
Labels: enhancement

#295 🐛 Fix bug when target name has plus sign
  Sources/Rugby/Utils/Regex/Regex.swift
  Tests/RugbyTests/Utils/Regex/RegexTests.swift
Labels: bug

#296 ⚙️ Add tests for `ProductHasher`
  Sources/RugbyFoundation/Core/Common/Hashers/ProductHasher.swift
  Sources/RugbyFoundation/Core/Common/Hashers/TargetsHasher.swift
  Sources/RugbyFoundation/Vault/Vault.swift
  Tests/FoundationTests/Core/Common/Hashers/ProductHasherTests.swift
  Tests/RugbyTests/Utils/Regex/RegexTests.swift
Labels: tests

#297 ⚙️ Add tests for `CocoaPodsScriptsHasher`
  Sources/RugbyFoundation/Core/Common/Hashers/CocoaPodsScriptsHasher.swift
  Sources/RugbyFoundation/Core/Common/Hashers/TargetsHasher.swift
  Tests/FoundationTests/Core/Common/Hashers/CocoaPodsScriptsHasherTests.swift
Labels: tests

#298 ⚙️ Add tests for `ConfigurationsHasher`
  Sources/RugbyFoundation/Core/Common/Hashers/ConfigurationsHasher.swift
  Sources/RugbyFoundation/Core/Common/Hashers/TargetsHasher.swift
  Sources/RugbyFoundation/Vault/Vault.swift
  Tests/FoundationTests/Core/Common/Hashers/ConfigurationsHasherTests.swift
Labels: tests
