Repository swiftyfinch/Rugby, pull requests merged in 2024-03, with the labels that each got.

#341 🐛 Copy reference to subproject before fixing relative path
  Sources/RugbyFoundation/XcodeProject/Extensions/XcodeProj/PBXProj/PBXProj+Dependencies.swift
Labels: bug

#343 ⚙️ Use value of parallelizable field from testplan targets
  Sources/RugbyFoundation/Core/Test/TestplanEditor.swift
  Tests/FoundationTests/Core/Test/TestplanEditorTests.swift
  Tests/FoundationTests/Mocks/ITestplanEditorMock.generated.swift
Labels: clean up

#345 🐛 Rewrite backup folders instead of copying files
  Sources/RugbyFoundation/Core/Rollback/BackupManager.swift
  Tests/FoundationTests/Core/Rollback/BackupManagerTests.swift
Labels: bug

#351 ⚙️ Add ability to mark test targets as passed if all tests are succeed
  .swiftlint.yml
  Sources/RugbyFoundation/Core/Test/TestManager.swift
  Sources/RugbyFoundation/Vault/Commands/Vault+Test.swift
  Tests/FoundationTests/Core/Test/TestManagerTests.swift
Labels: ⚙️ Tech

#358 🤖 Bump dependencies
  Package.resolved
  Package.swift
Labels: dependencies

#360 ⚙️ Warmup percents
  Sources/RugbyFoundation/Core/Warmup/WarmupManager.swift
  Tests/FoundationTests/Core/Warmup/WarmupManagerTests.swift
Labels: ⚙️ Engineering Task

#363 🚢 Add universal rugby release
  Makefile
Labels: ⚙️ Engineering Task

#364 ⚙️ Use AnyObject to optimise protocols
  Sources/Rugby/Utils/Concurrency/TimerTaskFactory.swift
  Sources/Rugby/Utils/Logger/Printers/StandardOutput.swift
  Sources/RugbyFoundation/Core/Build/Prebuild/PrebuildManager.swift
  Sources/RugbyFoundation/Core/Build/TargetTreePainter.swift
  Sources/RugbyFoundation/Core/Build/XcodeBuild/BuildLogFormatter.swift
  Sources/RugbyFoundation/Core/Build/XcodeBuild/XcodeBuildExecutor.swift
  Sources/RugbyFoundation/Core/Clear/Cleaner.swift
  Sources/RugbyFoundation/Core/Common/Hashers/FoundationHasher/SHA1FoundationHasher.swift
  Sources/RugbyFoundation/Core/Common/ProcessMonitor/ProcessMonitor.swift
  Sources/RugbyFoundation/Core/Common/Router.swift
  Sources/RugbyFoundation/Core/Common/Shell/ShellExecuter.swift
  Sources/RugbyFoundation/Core/Common/Shell/SoundPlayer.swift
  Sources/RugbyFoundation/Core/Delete/DeleteTargetsManager.swift
  Sources/RugbyFoundation/Core/Env/ArchitectureProvider.swift
  Sources/RugbyFoundation/Core/Env/EnvironmentCollector.swift
  Sources/RugbyFoundation/Core/Env/SwiftVersionProvider.swift
  Sources/RugbyFoundation/Core/Env/XcodeCLTVersionProvider.swift
  Sources/RugbyFoundation/Core/Plans/PlansParser.swift
  Sources/RugbyFoundation/Core/Rollback/BackupManager.swift
  Sources/RugbyFoundation/Core/Test/TestImpactManager.swift
  Sources/RugbyFoundation/Core/Test/TestManager.swift
  Sources/RugbyFoundation/Core/Test/TestplanEditor.swift
  Sources/RugbyFoundation/Core/Test/TestsStorage.swift
  Sources/RugbyFoundation/Core/Use/SupportFilesPatcher.swift
  Sources/RugbyFoundation/Core/Use/UseBinariesManager.swift
  Sources/RugbyFoundation/Core/Warmup/WarmupManager.swift
  Sources/RugbyFoundation/Utils/Public/Logger/Printers/IProgressPrinter.swift
  Sources/RugbyFoundation/Utils/Public/Logger/Printers/Printer.swift
  Sources/RugbyFoundation/XcodeProject/Services/XcodePhaseEditor.swift
  Sources/RugbyFoundation/XcodeProject/Services/XcodeProjectSchemesEditor.swift
  Sources/RugbyFoundation/XcodeProject/Services/XcodeWorkspaceEditor.swift
Labels: ⚙️ Engineering Task

#374 🐳 Improve remote cache documentation
  Docs/remote-cache.md
Labels: 📖 Docs

#377 🤖 Bump Fish to 0.1.2
  Package.resolved
  Package.swift
Labels: dependencies

#387 🚀 Improve 4XX error message management
  Sources/Rugby/Core/Dependencies/Update/GitHubReleaseListLoader.swift
Labels: 🚀 Enhancement

#388 🚀 Add ability to load latest release without api request
  Sources/Rugby/Core/Dependencies/Update/GitHubReleaseListLoader.swift
  Sources/Rugby/Core/Dependencies/Update/GitHubUpdater.swift
Labels: 🚀 Enhancement
